# Generated by Django 4.1.2 on 2022-11-02 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_like_user_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followeesu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followersu', to=settings.AUTH_USER_MODEL),
        ),
    ]
